export const ALL_SHOP_REQUEST = "ALL_SHOP_REQUEST";
export const ALL_SHOP_SUCCESS = "ALL_SHOP_SUCCESS";
export const ALL_SHOP_FAIL = "ALL_SHOP_FAIL";
export const NEW_SHOP_REQUEST = "NEW_SHOP_REQUEST";
export const NEW_SHOP_SUCCESS = "NEW_SHOP_SUCCESS";
export const NEW_SHOP_FAIL = "NEW_SHOP_FAIL";
export const NEW_SHOP_RESET = "NEW_SHOP_RESET";

export const ADMIN_SHOP_REQUEST = "ADMIN_SHOP_REQUEST";
export const ADMIN_SHOP_SUCCESS = "ADMIN_SHOP_SUCCESS";
export const ADMIN_SHOP_FAIL = "ADMIN_SHOP_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";